pipeline{

    agent any

    tools{
      maven 'Maven'
    }

    parameters {
    choice(name: 'ENVIRONMENT', choices: ['dev', 'prod'], description: 'Environment-Auswahl')
    }


    stages{

        stage("Checkout code from git"){
          steps{
            checkout scm
          }
        }
        
        stage("Build"){
          steps{
            dir('backend') {
              sh 'mvn clean package'
            }
          }
        }
    }


    post{
        always{
           echo "HI"
        }
        success{
            cleanWs()
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}
