pipeline{

    agent any

    tools{
      maven 'Maven'
    }

    parameters {
    choice(name: 'ENVIRONMENT', choices: ['dev', 'prod'], description: 'Environment-Auswahl')
    }


    stages{

         stage("Checkout code from git"){
          steps{
            checkout scm
          }
        }
        
        stage("Compile"){
          steps{
            sh "mvn compile"
          }
        }

        stage("Clean"){
          steps{
            sh "mvn clean package"
          }
        }
    }


    post{
        always{
            cleanWs()
        }
        success{
            cleanWs()
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}
